Feature/homework3
arisemcdc/MyRecipes pull request #3
Opened 2022-11-07 19:18 UTC by arisemcdc

Add Welcome, Registration, Login layout

2022-11-10 19:18 UTC, AndroidStudentClub commented
Проект не собирается
1) app/src/main/res/drawable/UserName.png - ругается на этот файл
Ошибка File-based resource names must contain only lowercase a-z, 0-9, or underscore
То есть ресурсы не могут быть с большой буквы - только lowercase a-z,

2022-11-10 19:30 UTC, AndroidStudentClub commented
<img width="1310" alt="Снимок экрана 2022-11-10 в 22 29 49" src="https://user-images.githubusercontent.com/12550867/201188697-4138b5b6-6bac-44be-a344-ad2a75306c4e.png">
Вобщем много ресурсов с некоректным названием - из-за этого проект не собирается. Нужно все переименовать

2022-11-10 19:38 UTC, AndroidStudentClub commented
Какие-то странные иконки экспортированы - ну нужно было их столько

2022-11-10 20:16 UTC, AndroidStudentClub requested changes
Много правок нужно
1) Поудалять лишние иконки
2) Привести название в порядок
3) Поправить xml-файлы (ошибки из-за которых не собирался проект все описал)
4) Доверстать
5) Сделать переходы между activity

2022-11-10 20:16 UTC, AndroidStudentClub commented on app/src/main/AndroidManifest.xml
> +            android:name=".WelcomeActivity"
Нужно сделать WelcomeActivity чтобы была лаунчером
Для этого нужно MainActivity поменять на WelcomeActivity как на примере:
     ```
<activity
            android:name=".WelcomeActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

2022-11-10 20:16 UTC, AndroidStudentClub commented on app/src/main/AndroidManifest.xml
> +            android:name=".WelcomeActivity"
А здесь поменять 
  <activity
            android:name=".WelcomeActivity"
На MainActivity

2022-11-10 20:16 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +        android:src = "@drawable/frying_pan_epmty_background"
Вот тут картинка немного неверно экспортирована
![main_back](https://user-images.githubusercontent.com/12550867/201195064-935c87b7-bb76-4b4b-8a8e-66fbbc29b2ca.jpg)
Вот эту надо

2022-11-10 20:16 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:layout_width="wrap_content"
Не, лучше сделать по всей ширине, но с отступами по 16 dp слева и справа
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="16dp"

2022-11-10 20:16 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +                android:layout_width="match_parent"
Не, лучше сделать по всей ширине, но с отступами по 16 dp слева и справа
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:layout_margin="16dp"

2022-11-10 20:16 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:layout_width="wrap_content"
Не, лучше сделать по всей ширине, но с отступами по 16 dp слева и справа
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:layout_margin="16dp"

2022-11-10 20:16 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/passwordText"
Можно впринципе везде TextInpulLayout сделать

2022-11-10 20:16 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/registrationButton"
Нужно еще переходы сделать из одной активити в другую
1) Начинается WelcomActivity
2) Потом по нажатию кнопки RegistrationActivity
3) Потом на Login Activity
4) Потом на MainActivity
<img width="870" alt="Снимок экрана 2022-11-10 в 23 12 43" src="https://user-images.githubusercontent.com/12550867/201196613-090fb62f-7a22-4d04-932a-4d5933a10895.png">

2022-11-12 20:04 UTC, arisemcdc commented on app/src/main/AndroidManifest.xml
> +            android:name=".WelcomeActivity"
Поменял, но почему-то не отображаются кнопки Регистрация и Войти как на Layout?
![Снимок51](https://user-images.githubusercontent.com/8739547/201492498-6f4b1968-996c-4a23-9284-c221ba73b6c0.PNG)

2022-11-12 20:12 UTC, arisemcdc commented on app/src/main/res/layout/activity_registration.xml
> +        android:src = "@drawable/frying_pan_epmty_background"
Если вставляю эту, то на просмотре вставляется на всю ширину, но при запуску вылетает с RuntimeException:
![Снимок52](https://user-images.githubusercontent.com/8739547/201492727-94269c7c-8498-4430-86ce-ea80bb65a171.PNG)

2022-11-12 21:14 UTC, arisemcdc commented on app/src/main/res/layout/activity_registration.xml
> +        android:src = "@drawable/frying_pan_epmty_background"
и почему-то после удаления картинок не удается push сделать на github. Выдает ошибку:
![Снимок54](https://user-images.githubusercontent.com/8739547/201494807-1d937bb3-ec7e-45ea-afcf-3bb0e006eb08.PNG)

2022-11-12 21:23 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +        android:src = "@drawable/frying_pan_epmty_background"
@arisemcdc  Это не связано с картинками - это что-то с доступом к гитхабу. Добавлен ssh-ключ?

2022-11-12 21:24 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +        android:src = "@drawable/frying_pan_epmty_background"
> Если вставляю эту, то на просмотре вставляется на всю ширину, но при запуску вылетает с RuntimeException: ![Снимок52](https://user-images.githubusercontent.com/8739547/201492727-94269c7c-8498-4430-86ce-ea80bb65a171.PNG)

Ошибка связана с тем, что очень жирная картинка - можно попробовать экспортировать ее в формате jpg она будет поменьше

2022-11-12 21:25 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +        android:src = "@drawable/frying_pan_epmty_background"
Там написано too large - слишком тяжелая картинка

2022-11-12 21:26 UTC, AndroidStudentClub commented on app/src/main/AndroidManifest.xml
> +            android:name=".WelcomeActivity"
Это какая активити? А точно этот layout соотвествует именно этой активити? И еще надо проверить какой родительский контейнер там

2022-11-25 18:18 UTC, merged